NumPy:
	
	NumPy is a Python library used for working with arrays.
	N-Dimensional Arrays: NumPy’s core feature is ndarray, a powerful N-dimensional array object that supports homogeneous data types.	
	Arrays with High Performance: Arrays are stored in contiguous memory locations, enabling faster computations than Python lists

In [9]:
import numpy as np

# 1D Array (One-dimensional) - Just a simple list of values
arr_one_dimensional = np.array([1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,6,6,6,
                                 7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,9,9,9,9,9,9,9,9,9])
print("1D Array:\n", arr_one_dimensional)

# 2D Array (Two-dimensional) - Like a table (rows x columns)
arr_two_dimensional = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("\n2D Array:\n", arr_two_dimensional)

# 3D Array (Three-dimensional) - Like a stack of 2D arrays
arr_three_dimensional = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr_three_dimensional)

1D Array:
 [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 9
 9 9 9 9 9 9 9 9]

2D Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# Single element access
print("Single element access:", arr_one_dimensional[2])  

# Negative indexing
print("Negative indexing:", arr_one_dimensional[-1])  

# Multidimensional array access
print("Multidimensional array access:", arr_two_dimensional[1, 0]) 

Single element access: 2
Negative indexing: 9
Multidimensional array access: 3


In [11]:
# elements from index 4 to 10
print("Elements from index 4 to 10:", arr_one_dimensional[4:11])

#all rows, second column
print("Multidimensional Slicing:", arr_two_dimensional[:, 1])

# Reverse array elements
print("Reverse array elements:", arr_one_dimensional[::-1])

Elements from index 4 to 10: [3 3 4 4 4 4 5]
Multidimensional Slicing: [2 4 6 8]
Reverse array elements: [9 9 9 9 9 9 9 9 9 8 8 8 8 8 8 8 8 7 7 7 7 7 7 7 6 6 6 6 6 6 5 5 5 5 5 4 4
 4 4 3 3 3 2 2 1]


In [12]:
# Conditional index
for i in range(0, 11):
    print("Element at index {} is {}".format(i, arr_one_dimensional[i]))

Element at index 0 is 1
Element at index 1 is 2
Element at index 2 is 2
Element at index 3 is 3
Element at index 4 is 3
Element at index 5 is 3
Element at index 6 is 4
Element at index 7 is 4
Element at index 8 is 4
Element at index 9 is 4
Element at index 10 is 5


NumPy Basic Operations

    Element-wise Operations: Addition, subtraction, multiplication, and division directly on NumPy arrays.

In [13]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# 1. Element-wise operations (each element of x with corresponding y)
print("Addition:", x + y)             
print("Subtraction:", x - y)        
print("Multiplication:", x * y)      
print("Division:", x / y)            

# 2. Dot Product (used in linear models, weighted sum)
dot_product = np.dot(x, y)            # 1*4 + 2*5 + 3*6 = 32
print("Dot Product:", dot_product)

# 3. Statistics (common in data analysis and normalization)
print("Mean of x:", np.mean(x))       # Average of [1,2,3]
print("Std dev of y:", np.std(y))     # Measure of spread
print("Sum of x:", np.sum(x))         # Total of array x

# 4. Vector norm (L2 norm, used in optimization & distance calculation)
norm = np.linalg.norm(x)
print("L2 Norm of x:", norm)

# 5. Reshape array (important for feeding data into ML models)
x_reshaped = x.reshape(3, 1)          # Convert from (3,) to (3,1)
print("Reshaped x:\n", x_reshaped)

# 6. Stack arrays (combine feature vectors or batches)
print("Horizontal Stack:\n", np.hstack((x, y)))  # Side by side
print("Vertical Stack:\n", np.vstack((x, y)))    # One below other

# 7. Logical operations (filtering based on condition)
print("x > 1:", x > 1)                      # Boolean array
print("Elements in x > 1:", x[x > 1])       # [2, 3]


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Dot Product: 32
Mean of x: 2.0
Std dev of y: 0.816496580927726
Sum of x: 6
L2 Norm of x: 3.7416573867739413
Reshaped x:
 [[1]
 [2]
 [3]]
Horizontal Stack:
 [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]
x > 1: [False  True  True]
Elements in x > 1: [2 3]
